function HexSettings()
	SettingsMainframe = vgui.Create("DFrame")
	SettingsMainframe:SetSize(400,300)
	SettingsMainframe:SetPos( (ScrW()/2)-200, (ScrH()/2)-150 )
	SettingsMainframe:SetTitle("Client Settings")
	SettingsMainframe:SetVisible( true )
	SettingsMainframe:SetDraggable( false )
	SettingsMainframe:ShowCloseButton( true )
	SettingsMainframe:MakePopup()
	SettingsMainframe.Paint = function()
		draw.RoundedBox( 8, 0, 0, SettingsMainframe:GetWide(), SettingsMainframe:GetTall(), Color( 135, 145, 155, 100 ) )
	end

	local ab1 = vgui.Create( "DNumSlider", SettingsMainframe )
	ab1:SetPos( 25,200 )
	ab1:SetSize( 300, 50 )
	ab1:SetText( "Third Person Position - X" )
	ab1:SetMin( -80 )
	ab1:SetMax( 80 )
	ab1:SetDecimals( 0 )
	ab1:SetConVar( "hex_cl_thirdpersonpositionx" )
	ab1:SizeToContents()
	ab1.OnValueChanged = function()
		ab1:SetValue( math.Clamp(ab1:GetValue(),-80,80) )
	end

	local ab2 = vgui.Create( "DNumSlider", SettingsMainframe )
	ab2:SetPos( 25,240 )
	ab2:SetSize( 300, 50 )
	ab2:SetText( "Third Person Position - Y" )
	ab2:SetMin( -30 )
	ab2:SetMax( 15 )
	ab2:SetDecimals( 0 )
	ab2:SetConVar( "hex_cl_thirdpersonpositiony" )
	ab2:SizeToContents()
	ab2.OnValueChanged = function()
		ab2:SetValue( math.Clamp(ab2:GetValue(),-30,15) )
	end

	local bc = vgui.Create( "DCheckBoxLabel", SettingsMainframe )
	bc:SetPos( 200,40 )
	bc:SetText( "Toggle Chat Sounds" )
	bc:SetConVar( "hex_cl_togglechatsound" )
	bc:SetValue( 1 )
	bc:SizeToContents()

	local ad = vgui.Create( "DCheckBoxLabel", SettingsMainframe )
	ad:SetPos( 25,65 )
	ad:SetText( "Toggle Pickup Light" )
	ad:SetConVar( "hex_cl_togglepickuplight" )
	ad:SetValue( 1 )
	ad:SizeToContents()

	local bd = vgui.Create( "DCheckBoxLabel", SettingsMainframe )
	bd:SetPos( 200,65 )
	bd:SetText( "Toggle 2D Particles" )
	bd:SetConVar( "hex_cl_toggle2dparticles" )
	bd:SetValue( 1 )
	bd:SizeToContents()

	local ae = vgui.Create( "DCheckBoxLabel", SettingsMainframe )
	ae:SetPos( 25,90 )
	ae:SetText( "Toggle Damage Numbers" )
	ae:SetConVar( "hex_cl_toggledamagenumbers" )
	ae:SetValue( 1 )
	ae:SizeToContents()

	local be = vgui.Create( "DCheckBoxLabel", SettingsMainframe )
	be:SetPos( 200,90 )
	be:SetText( "Toggle Crosshair Indicators" )
	be:SetConVar( "hex_cl_togglecrosshairindicator" )
	be:SetValue( 1 )
	be:SizeToContents()	
end
usermessage.Hook("SendHexSettings",HexSettings)